name: Test Detox iOS

on:
  pull_request:

jobs:
  test-detox-ios:
    runs-on: macos-latest
    timeout-minutes: 60
    permissions:
      checks: read
      contents: read
    steps:
      - name: âŒ› Wait for build to finish
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delay: 20s
          match_pattern: build-release-ios

      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸŒ¿ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: ğŸ“¦ Install dependencies
        run: yarn install --immutable

      - name: ğŸ“¦ Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: ğŸ› Try to restore build from cache
        id: ios-release-restore
        uses: actions/cache/restore@v4
        with:
          path: ios-release-build/
          key: ios-release-build-${{ github.event.pull_request.head.sha }}

      - name: ğŸ“‹ Run Detox tests
        run: yarn detox:test:ios
